name: build

on:
  pull_request:
    branches: ["main"]

jobs:
  tox:
    uses: ./.github/workflows/tox.yml
    secrets: inherit
  docker:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
