name: build

on:
  pull_request:
    branches: ["main"]

jobs:
  tox:
    uses: ./.github/workflows/tox.yml
    secrets: inherit
  docker-build:
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
