name: Build Docker Container

on:
  workflow_call:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'
    - name: Build the Docker Container
      run: docker build . --file Dockerfile --tag osml-model-runner:$(date +%s)
