name: Docker Image Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: 'true'
        ssh-key: ${{ secrets.git_ssh_key }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag osml-model-runner:$(date +%s)
