name: "OSML Model Runner Build and Publish Workflow"

on:
  push:
    branches: ["main", "dev"]

jobs:
  Build_Validate_Tox:
    uses: ./.github/workflows/python-tox.yml
    secrets: inherit
  Build_Docker_Container:
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
  Publish_Python:
    needs: [Build_Validate_Tox, Build_Docker_Container]
    uses: ./.github/workflows/python-publish.yml
    secrets: inherit
  Publish_Docker_Dockerhub:
    needs: [Build_Validate_Tox, Build_Docker_Container]
    uses: ./.github/workflows/docker-publish-dockerhub.yml
    secrets: inherit
  Publish_Docker_Github:
    needs: [Build_Validate_Tox, Build_Docker_Container]
    uses: ./.github/workflows/docker-publish-github.yml
    secrets: inherit
  Publish_Documentation:
    needs: [Publish_Python, Publish_Docker_Github, Publish_Docker_Dockerhub]
    uses: ./.github/workflows/documentation-publish.yml
    secrets: inherit
  Notify_Guidance_Repo:
    needs: [Publish_Docker_Github, Publish_Docker_Dockerhub]
    uses: ./.github/workflows/notify-guidance-repo.yml
    secrets: inherit
